import type { CatalystPlayer } from '@shared/types/catalyst';
import { getTier } from '@/components/catalyst/utils';

function escapeCsvCell(value: string | number): string {
  const text = String(value);
  if (!/[",\n\r]/.test(text)) return text;
  return `"${text.replace(/"/g, '""')}"`;
}

export function buildCatalystCsv(position: string, season: number, players: CatalystPlayer[]): string {
  const headers = [
    'rank', 'player_name', 'position', 'team',
    'catalyst_alpha', 'tier', 'catalyst_raw',
    'plays', 'avg_leverage', 'opponent_factor', 'script_factor',
    'recency_factor', 'base_epa_sum', 'weighted_epa_sum',
  ];

  const metaRows = [
    `# CATALYST Lab Export — ${position} — ${season} Season`,
    '# Generated by TIBER | Contextual Adaptive Tactical Leverage Yield Score',
    '# Tiers: Elite Clutch (85+) | Clutch (65–84) | Neutral (45–64) | Low Signal (25–44) | Garbage Time Risk (<25)',
    '# catalyst_alpha: 0–100 percentile within position group',
    '# catalyst_raw: weighted EPA per play (EPA × leverage × opponent × game_script × recency)',
    '',
  ];

  const rows = players.map((p, i) => {
    const tier = getTier(p.catalyst_alpha);
    return [
      i + 1,
      p.player_name,
      p.position,
      p.team,
      p.catalyst_alpha.toFixed(1),
      tier.label,
      p.catalyst_raw.toFixed(4),
      p.components.play_count,
      p.components.avg_leverage.toFixed(4),
      p.components.opponent_factor.toFixed(4),
      p.components.script_factor.toFixed(4),
      p.components.recency_factor.toFixed(4),
      p.components.base_epa_sum.toFixed(2),
      p.components.weighted_epa_sum.toFixed(2),
    ].map(escapeCsvCell).join(',');
  });

  return [...metaRows, headers.join(','), ...rows].join('\n');
}

export function downloadCatalystCsv(position: string, season: number, players: CatalystPlayer[]): void {
  const csv = buildCatalystCsv(position, season, players);
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `catalyst_${position.toLowerCase()}_${season}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}
