import {
  TIBER_MATRIX_ROLE_ONTOLOGY_VERSION,
  type RoleOntology,
  type RoleOntologyEntry,
  type TiberMatrixRoleId,
} from '@shared/types/roleOntology';

const role = (entry: RoleOntologyEntry): [TiberMatrixRoleId, RoleOntologyEntry] => [entry.role_id, entry];

export const TIBER_MATRIX_ROLE_ONTOLOGY_V1: RoleOntology = {
  version: TIBER_MATRIX_ROLE_ONTOLOGY_VERSION,
  roles: Object.fromEntries([
    role({
      role_id: 'QB_STRUCTURED_DISTRIBUTOR',
      position: 'QB',
      family: 'Quarterback',
      label: 'Structured Distributor',
      description: 'Pocket-first passer with low designed run load and controlled target depth.',
      key_metrics: ['designed_rush_rate', 'scramble_rate', 'third_down_snap_rate', 'adot'],
    }),
    role({
      role_id: 'QB_BALANCED_CREATOR',
      position: 'QB',
      family: 'Quarterback',
      label: 'Balanced Creator',
      description: 'Pass-first QB with meaningful improvisation but not a run-engine profile.',
      key_metrics: ['scramble_rate', 'deep_target_rate', 'adot', 'two_minute_snap_rate'],
    }),
    role({
      role_id: 'QB_DUAL_THREAT_ENGINE',
      position: 'QB',
      family: 'Quarterback',
      label: 'Dual Threat Engine',
      description: 'High-rush-usage QB that drives offense with designed and scramble rushing.',
      key_metrics: ['designed_rush_rate', 'scramble_rate', 'goal_line_carry_share', 'deep_target_rate'],
    }),
    role({
      role_id: 'RB_WORKHORSE_GRINDER',
      position: 'RB',
      family: 'Running Back',
      label: 'Workhorse Grinder',
      description: 'Early-down heavy back with strong carry share and modest receiving usage.',
      key_metrics: ['carry_share', 'route_rate', 'third_down_snap_rate', 'goal_line_carry_share'],
    }),
    role({
      role_id: 'RB_HYBRID_BELL_COW',
      position: 'RB',
      family: 'Running Back',
      label: 'Hybrid Bell Cow',
      description: 'High-volume back active across early downs, passing downs, and red zone.',
      key_metrics: ['carry_share', 'route_rate', 'third_down_snap_rate', 'two_minute_snap_rate'],
    }),
    role({
      role_id: 'RB_SATELLITE_PLUS',
      position: 'RB',
      family: 'Running Back',
      label: 'Satellite Plus',
      description: 'Passing-game RB with high route and long-down usage and lower rushing share.',
      key_metrics: ['route_rate', 'third_down_snap_rate', 'two_minute_snap_rate', 'carry_share'],
    }),
    role({
      role_id: 'RB_GOAL_LINE_HAMMER',
      position: 'RB',
      family: 'Running Back',
      label: 'Goal Line Hammer',
      description: 'Specialized short-yardage/TD RB with concentrated goal-line carries.',
      key_metrics: ['goal_line_carry_share', 'red_zone_carry_share', 'route_rate', 'carry_share'],
    }),
    role({
      role_id: 'RB_CHANGE_OF_PACE',
      position: 'RB',
      family: 'Running Back',
      label: 'Change of Pace',
      description: 'Lower-volume rotational RB used in selective packages and motion looks.',
      key_metrics: ['carry_share', 'motion_rate', 'route_rate', 'two_minute_snap_rate'],
    }),
    role({
      role_id: 'WR_ALPHA_BOUNDARY_X',
      position: 'WR',
      family: 'Wide Receiver',
      label: 'Alpha Boundary X',
      description: 'High-route boundary WR with meaningful red-zone command.',
      key_metrics: ['boundary_rate', 'route_participation', 'red_zone_target_share', 'adot'],
    }),
    role({
      role_id: 'WR_VERTICAL_X',
      position: 'WR',
      family: 'Wide Receiver',
      label: 'Vertical X',
      description: 'Boundary WR specializing in deep targets and high aDOT routes.',
      key_metrics: ['boundary_rate', 'deep_target_rate', 'adot', 'route_participation'],
    }),
    role({
      role_id: 'WR_FLANKER_CHAIN_MOVER',
      position: 'WR',
      family: 'Wide Receiver',
      label: 'Flanker Chain Mover',
      description: 'Perimeter/intermediate WR earning steady routes with short-to-mid target profile.',
      key_metrics: ['boundary_rate', 'adot', 'route_participation', 'third_down_snap_rate'],
    }),
    role({
      role_id: 'WR_BIG_SLOT_HUB',
      position: 'WR',
      family: 'Wide Receiver',
      label: 'Big Slot Hub',
      description: 'Heavy-slot receiver with strong route share and red-zone target relevance.',
      key_metrics: ['slot_rate', 'route_participation', 'red_zone_target_share', 'adot'],
    }),
    role({
      role_id: 'WR_FIELD_STRETCH_Z',
      position: 'WR',
      family: 'Wide Receiver',
      label: 'Field Stretch Z',
      description: 'Z alignment speed receiver used to stress coverage vertically.',
      key_metrics: ['deep_target_rate', 'motion_rate', 'boundary_rate', 'adot'],
    }),
    role({
      role_id: 'WR_SLOT_GADGET',
      position: 'WR',
      family: 'Wide Receiver',
      label: 'Slot Gadget',
      description: 'Motion-heavy slot WR with manufactured-touch deployment and lower route load.',
      key_metrics: ['slot_rate', 'motion_rate', 'route_participation', 'adot'],
    }),
    role({
      role_id: 'TE_INLINE_ANCHOR',
      position: 'TE',
      family: 'Tight End',
      label: 'Inline Anchor',
      description: 'Inline TE with lower route volume and strong run-game attachment.',
      key_metrics: ['inline_rate', 'route_participation', 'adot', 'red_zone_target_share'],
    }),
    role({
      role_id: 'TE_MOVE_MISMATCH',
      position: 'TE',
      family: 'Tight End',
      label: 'Move Mismatch',
      description: 'Route-oriented TE deployed flexed/off-ball to create coverage mismatches.',
      key_metrics: ['inline_rate', 'route_participation', 'adot', 'slot_rate'],
    }),
    role({
      role_id: 'TE_RED_ZONE_POWER',
      position: 'TE',
      family: 'Tight End',
      label: 'Red Zone Power',
      description: 'Touchdown-specialist TE with concentrated red-zone target role.',
      key_metrics: ['red_zone_target_share', 'inline_rate', 'route_participation', 'adot'],
    }),
  ]) as RoleOntology['roles'],
};
