import {
  TIBER_MATRIX_ROLE_ONTOLOGY_VERSION,
  type RoleOntology,
  type RoleOntologyEntry,
  type TiberMatrixRoleId,
} from '@shared/types/roleOntology';

const role = (entry: RoleOntologyEntry): [TiberMatrixRoleId, RoleOntologyEntry] => [entry.role_id, entry];

export const TIBER_MATRIX_ROLE_ONTOLOGY_V1: RoleOntology = {
  version: TIBER_MATRIX_ROLE_ONTOLOGY_VERSION,
  roles: Object.fromEntries([
    // ── Quarterbacks ──────────────────────────────────────────────────────
    role({
      role_id: 'QB_STRUCTURED_DISTRIBUTOR',
      position: 'QB',
      family: 'Quarterback',
      label: 'Structured Distributor',
      description: 'Pocket-first passer with low designed run load and controlled target depth.',
      key_metrics: ['designed_rush_rate', 'scramble_rate', 'third_down_snap_rate', 'adot'],
      short_definition: 'Pure pocket passer who operates within structure, relying on timing and accuracy over improvisation.',
      usage_signature: {
        elevated: ['third_down_snap_rate', 'two_minute_snap_rate'],
        suppressed: ['designed_rush_rate', 'scramble_rate', 'deep_target_rate'],
      },
      core_traits: ['pocket presence', 'rhythm passing', 'pre-snap reads', 'check-down willingness'],
      opportunity_profile: { snap_share: 'FULL', pass_game_involved: true, rush_game_involved: false, red_zone_relevant: true },
      stability_profile: { week_to_week: 'HIGH', season_to_season: 'HIGH', scheme_sensitive: true },
      fantasy_translation: {
        upside_driver: 'Passing volume and TD efficiency',
        floor_profile: 'High floor from consistent volume, limited rushing upside',
        best_formats: ['redraft', 'bestball'],
      },
      common_failure_modes: ['offensive line collapse', 'lack of rushing floor', 'game-script negative regression'],
      common_upside_triggers: ['elite WR corps', 'high-pace offense', 'favorable schedule'],
      fallback_adjacent_roles: ['QB_BALANCED_CREATOR'],
    }),
    role({
      role_id: 'QB_BALANCED_CREATOR',
      position: 'QB',
      family: 'Quarterback',
      label: 'Balanced Creator',
      description: 'Pass-first QB with meaningful improvisation but not a run-engine profile.',
      key_metrics: ['scramble_rate', 'deep_target_rate', 'adot', 'two_minute_snap_rate'],
      short_definition: 'Pass-first QB who extends plays and creates outside structure without being a designed runner.',
      usage_signature: {
        elevated: ['scramble_rate', 'deep_target_rate'],
        suppressed: [],
      },
      core_traits: ['play extension', 'off-platform accuracy', 'controlled aggression', 'situational rushing'],
      opportunity_profile: { snap_share: 'FULL', pass_game_involved: true, rush_game_involved: false, red_zone_relevant: true },
      stability_profile: { week_to_week: 'MEDIUM', season_to_season: 'MEDIUM', scheme_sensitive: false },
      fantasy_translation: {
        upside_driver: 'Passing efficiency plus opportunistic rushing TDs',
        floor_profile: 'Moderate floor with scramble yards providing cushion',
        best_formats: ['redraft', 'dynasty', 'bestball'],
      },
      common_failure_modes: ['hero-ball tendencies', 'sack rate spikes', 'inconsistent deep ball accuracy'],
      common_upside_triggers: ['weak secondaries on schedule', 'improved OL enabling extended plays', 'aggressive play-caller'],
      fallback_adjacent_roles: ['QB_STRUCTURED_DISTRIBUTOR', 'QB_DUAL_THREAT_ENGINE'],
    }),
    role({
      role_id: 'QB_DUAL_THREAT_ENGINE',
      position: 'QB',
      family: 'Quarterback',
      label: 'Dual Threat Engine',
      description: 'High-rush-usage QB that drives offense with designed and scramble rushing.',
      key_metrics: ['designed_rush_rate', 'scramble_rate', 'goal_line_carry_share', 'deep_target_rate'],
      short_definition: 'Run-heavy QB whose designed and improvised rushing creates a distinct fantasy profile.',
      usage_signature: {
        elevated: ['designed_rush_rate', 'scramble_rate', 'goal_line_carry_share'],
        suppressed: [],
      },
      core_traits: ['designed runs', 'scramble ability', 'red-zone rushing', 'deep-ball aggression'],
      opportunity_profile: { snap_share: 'FULL', pass_game_involved: true, rush_game_involved: true, red_zone_relevant: true },
      stability_profile: { week_to_week: 'MEDIUM', season_to_season: 'LOW', scheme_sensitive: false },
      fantasy_translation: {
        upside_driver: 'Rushing volume and rushing TDs provide elite ceiling',
        floor_profile: 'High floor from rushing yards even in bad passing games',
        best_formats: ['dynasty', 'redraft', 'bestball'],
      },
      common_failure_modes: ['injury risk from rushing exposure', 'passing efficiency regression', 'offensive line dysfunction'],
      common_upside_triggers: ['goal-line rushing role', 'high red-zone rushing share', 'improved passing game efficiency'],
      fallback_adjacent_roles: ['QB_BALANCED_CREATOR'],
    }),

    // ── Running Backs ─────────────────────────────────────────────────────
    role({
      role_id: 'RB_WORKHORSE_GRINDER',
      position: 'RB',
      family: 'Running Back',
      label: 'Workhorse Grinder',
      description: 'Early-down heavy back with strong carry share and modest receiving usage.',
      key_metrics: ['carry_share', 'route_rate', 'third_down_snap_rate', 'goal_line_carry_share'],
      short_definition: 'Volume-based early-down rusher who dominates carry share but has limited pass-game involvement.',
      usage_signature: {
        elevated: ['carry_share', 'goal_line_carry_share', 'red_zone_carry_share'],
        suppressed: ['route_rate', 'third_down_snap_rate', 'two_minute_snap_rate'],
      },
      core_traits: ['between-the-tackles running', 'early-down dominance', 'short-yardage reliability', 'wear-down style'],
      opportunity_profile: { snap_share: 'PARTIAL', pass_game_involved: false, rush_game_involved: true, red_zone_relevant: true },
      stability_profile: { week_to_week: 'HIGH', season_to_season: 'MEDIUM', scheme_sensitive: true },
      fantasy_translation: {
        upside_driver: 'Rushing volume and goal-line TDs',
        floor_profile: 'Consistent rushing volume provides reliable floor',
        best_formats: ['redraft'],
      },
      common_failure_modes: ['game-script abandonment', 'negative stacked fronts', 'losing goal-line work'],
      common_upside_triggers: ['positive game scripts', 'weak run defenses', 'goal-line role expansion'],
      fallback_adjacent_roles: ['RB_HYBRID_BELL_COW', 'RB_GOAL_LINE_HAMMER'],
    }),
    role({
      role_id: 'RB_HYBRID_BELL_COW',
      position: 'RB',
      family: 'Running Back',
      label: 'Hybrid Bell Cow',
      description: 'High-volume back active across early downs, passing downs, and red zone.',
      key_metrics: ['carry_share', 'route_rate', 'third_down_snap_rate', 'two_minute_snap_rate'],
      short_definition: 'Complete three-down back who commands both rushing and receiving workload.',
      usage_signature: {
        elevated: ['carry_share', 'route_rate', 'third_down_snap_rate', 'two_minute_snap_rate'],
        suppressed: [],
      },
      core_traits: ['three-down usage', 'route running', 'pass protection', 'volume tolerance'],
      opportunity_profile: { snap_share: 'FULL', pass_game_involved: true, rush_game_involved: true, red_zone_relevant: true },
      stability_profile: { week_to_week: 'HIGH', season_to_season: 'MEDIUM', scheme_sensitive: false },
      fantasy_translation: {
        upside_driver: 'Dual rushing/receiving volume creates elite PPR ceiling',
        floor_profile: 'Very high floor from volume in both phases',
        best_formats: ['dynasty', 'redraft', 'bestball'],
      },
      common_failure_modes: ['workload regression from fatigue', 'committee emergence', 'passing-game efficiency drops'],
      common_upside_triggers: ['target volume spikes', 'goal-line role', 'weak defenses on schedule'],
      fallback_adjacent_roles: ['RB_WORKHORSE_GRINDER', 'RB_SATELLITE_PLUS'],
    }),
    role({
      role_id: 'RB_SATELLITE_PLUS',
      position: 'RB',
      family: 'Running Back',
      label: 'Satellite Plus',
      description: 'Passing-game RB with high route and long-down usage and lower rushing share.',
      key_metrics: ['route_rate', 'third_down_snap_rate', 'two_minute_snap_rate', 'carry_share'],
      short_definition: 'Receiving-specialist RB who earns fantasy value through targets and passing-down deployment.',
      usage_signature: {
        elevated: ['route_rate', 'third_down_snap_rate', 'two_minute_snap_rate', 'target_share'],
        suppressed: ['carry_share', 'goal_line_carry_share'],
      },
      core_traits: ['route running', 'pass catching', 'space creation', 'situational deployment'],
      opportunity_profile: { snap_share: 'PARTIAL', pass_game_involved: true, rush_game_involved: false, red_zone_relevant: false },
      stability_profile: { week_to_week: 'MEDIUM', season_to_season: 'LOW', scheme_sensitive: true },
      fantasy_translation: {
        upside_driver: 'PPR target volume in passing situations',
        floor_profile: 'Moderate floor tied to passing-game opportunity',
        best_formats: ['redraft', 'bestball'],
      },
      common_failure_modes: ['game-script positive (rush-heavy) weeks', 'target competition from WR/TE', 'efficiency volatility'],
      common_upside_triggers: ['negative game scripts', 'high-volume passing offense', 'injuries to RB1'],
      fallback_adjacent_roles: ['RB_HYBRID_BELL_COW', 'RB_CHANGE_OF_PACE'],
    }),
    role({
      role_id: 'RB_GOAL_LINE_HAMMER',
      position: 'RB',
      family: 'Running Back',
      label: 'Goal Line Hammer',
      description: 'Specialized short-yardage/TD RB with concentrated goal-line carries.',
      key_metrics: ['goal_line_carry_share', 'red_zone_carry_share', 'route_rate', 'carry_share'],
      short_definition: 'Short-yardage and goal-line specialist whose fantasy value is heavily TD-dependent.',
      usage_signature: {
        elevated: ['goal_line_carry_share', 'red_zone_carry_share'],
        suppressed: ['route_rate', 'third_down_snap_rate', 'two_minute_snap_rate'],
      },
      core_traits: ['goal-line power', 'short-yardage conversion', 'red-zone presence', 'limited between-the-20s role'],
      opportunity_profile: { snap_share: 'SPECIALIST', pass_game_involved: false, rush_game_involved: true, red_zone_relevant: true },
      stability_profile: { week_to_week: 'LOW', season_to_season: 'LOW', scheme_sensitive: true },
      fantasy_translation: {
        upside_driver: 'Touchdown volume from goal-line carries',
        floor_profile: 'Very low floor without TDs; boom-bust profile',
        best_formats: ['bestball'],
      },
      common_failure_modes: ['TD variance', 'lost goal-line role to primary back', 'low overall snap count'],
      common_upside_triggers: ['team scores frequently', 'primary back injury', 'expanded early-down role'],
      fallback_adjacent_roles: ['RB_WORKHORSE_GRINDER', 'RB_CHANGE_OF_PACE'],
    }),
    role({
      role_id: 'RB_CHANGE_OF_PACE',
      position: 'RB',
      family: 'Running Back',
      label: 'Change of Pace',
      description: 'Lower-volume rotational RB used in selective packages and motion looks.',
      key_metrics: ['carry_share', 'motion_rate', 'route_rate', 'two_minute_snap_rate'],
      short_definition: 'Low-volume rotational back with scheme-specific or change-of-pace usage.',
      usage_signature: {
        elevated: ['motion_rate'],
        suppressed: ['carry_share', 'goal_line_carry_share', 'red_zone_carry_share'],
      },
      core_traits: ['burst/speed complement', 'motion deployment', 'limited but targeted usage', 'upside-only profile'],
      opportunity_profile: { snap_share: 'SPECIALIST', pass_game_involved: false, rush_game_involved: true, red_zone_relevant: false },
      stability_profile: { week_to_week: 'LOW', season_to_season: 'LOW', scheme_sensitive: true },
      fantasy_translation: {
        upside_driver: 'Explosive play potential in limited touches',
        floor_profile: 'Very low floor; heavily dependent on efficiency or breakaway runs',
        best_formats: ['bestball'],
      },
      common_failure_modes: ['volume too low for consistency', 'lost role to other backups', 'coaching changes'],
      common_upside_triggers: ['RB1 injury', 'expanded role in high-pace offense', 'special-teams return value'],
      fallback_adjacent_roles: ['RB_SATELLITE_PLUS', 'RB_GOAL_LINE_HAMMER'],
    }),

    // ── Wide Receivers ────────────────────────────────────────────────────
    role({
      role_id: 'WR_ALPHA_BOUNDARY_X',
      position: 'WR',
      family: 'Wide Receiver',
      label: 'Alpha Boundary X',
      description: 'High-route boundary WR with meaningful red-zone command.',
      key_metrics: ['boundary_rate', 'route_participation', 'red_zone_target_share', 'adot'],
      short_definition: 'Team WR1 who wins contested catches on the boundary and commands red-zone targets.',
      usage_signature: {
        elevated: ['boundary_rate', 'route_participation', 'red_zone_target_share', 'target_share'],
        suppressed: ['motion_rate', 'screen_target_rate'],
      },
      core_traits: ['contested catching', 'route-running precision', 'red-zone dominance', 'boundary alignment'],
      opportunity_profile: { snap_share: 'FULL', pass_game_involved: true, rush_game_involved: false, red_zone_relevant: true },
      stability_profile: { week_to_week: 'HIGH', season_to_season: 'HIGH', scheme_sensitive: false },
      fantasy_translation: {
        upside_driver: 'Target volume plus red-zone TD equity',
        floor_profile: 'High floor from route participation and target share',
        best_formats: ['dynasty', 'redraft', 'bestball'],
      },
      common_failure_modes: ['shadow coverage from top CB', 'target competition from new additions', 'QB regression'],
      common_upside_triggers: ['target share consolidation', 'favorable secondary matchups', 'elite QB play'],
      fallback_adjacent_roles: ['WR_VERTICAL_X', 'WR_FLANKER_CHAIN_MOVER'],
    }),
    role({
      role_id: 'WR_VERTICAL_X',
      position: 'WR',
      family: 'Wide Receiver',
      label: 'Vertical X',
      description: 'Boundary WR specializing in deep targets and high aDOT routes.',
      key_metrics: ['boundary_rate', 'deep_target_rate', 'adot', 'route_participation'],
      short_definition: 'Deep-ball specialist on the boundary whose value is tied to vertical shot plays.',
      usage_signature: {
        elevated: ['boundary_rate', 'deep_target_rate', 'adot'],
        suppressed: ['screen_target_rate', 'slot_rate'],
      },
      core_traits: ['deep speed', 'tracking ability', 'boundary release', 'vertical route tree'],
      opportunity_profile: { snap_share: 'FULL', pass_game_involved: true, rush_game_involved: false, red_zone_relevant: false },
      stability_profile: { week_to_week: 'LOW', season_to_season: 'MEDIUM', scheme_sensitive: true },
      fantasy_translation: {
        upside_driver: 'Explosive plays from deep targets; high per-target value',
        floor_profile: 'Low floor; dependent on deep-ball connection rate',
        best_formats: ['bestball'],
      },
      common_failure_modes: ['deep-ball variance', 'poor QB deep accuracy', 'bracket coverage'],
      common_upside_triggers: ['QB with strong deep ball', 'high-pace offense', 'single-high safety matchups'],
      fallback_adjacent_roles: ['WR_ALPHA_BOUNDARY_X', 'WR_FIELD_STRETCH_Z'],
    }),
    role({
      role_id: 'WR_FLANKER_CHAIN_MOVER',
      position: 'WR',
      family: 'Wide Receiver',
      label: 'Flanker Chain Mover',
      description: 'Perimeter/intermediate WR earning steady routes with short-to-mid target profile.',
      key_metrics: ['boundary_rate', 'adot', 'route_participation', 'third_down_snap_rate'],
      short_definition: 'Reliable possession WR who operates at short-to-intermediate depth and sustains drives.',
      usage_signature: {
        elevated: ['route_participation', 'third_down_snap_rate'],
        suppressed: ['deep_target_rate', 'motion_rate'],
      },
      core_traits: ['route precision', 'chain-moving reliability', 'YAC ability', 'intermediate zone work'],
      opportunity_profile: { snap_share: 'FULL', pass_game_involved: true, rush_game_involved: false, red_zone_relevant: false },
      stability_profile: { week_to_week: 'HIGH', season_to_season: 'HIGH', scheme_sensitive: false },
      fantasy_translation: {
        upside_driver: 'Target volume and catch rate in PPR formats',
        floor_profile: 'High floor from consistent targets; lower ceiling from aDOT',
        best_formats: ['redraft', 'dynasty'],
      },
      common_failure_modes: ['TD drought from low aDOT', 'target share compression', 'limited explosive plays'],
      common_upside_triggers: ['target share spike from injuries', 'improved red-zone role', 'YAC-friendly scheme'],
      fallback_adjacent_roles: ['WR_BIG_SLOT_HUB', 'WR_ALPHA_BOUNDARY_X'],
    }),
    role({
      role_id: 'WR_BIG_SLOT_HUB',
      position: 'WR',
      family: 'Wide Receiver',
      label: 'Big Slot Hub',
      description: 'Heavy-slot receiver with strong route share and red-zone target relevance.',
      key_metrics: ['slot_rate', 'route_participation', 'red_zone_target_share', 'adot'],
      short_definition: 'High-volume slot WR who commands targets from the inside and converts in the red zone.',
      usage_signature: {
        elevated: ['slot_rate', 'route_participation', 'red_zone_target_share', 'target_share'],
        suppressed: ['deep_target_rate'],
      },
      core_traits: ['slot route running', 'size mismatch inside', 'red-zone presence', 'high-volume target profile'],
      opportunity_profile: { snap_share: 'FULL', pass_game_involved: true, rush_game_involved: false, red_zone_relevant: true },
      stability_profile: { week_to_week: 'HIGH', season_to_season: 'HIGH', scheme_sensitive: false },
      fantasy_translation: {
        upside_driver: 'Target volume from slot plus red-zone TDs',
        floor_profile: 'High floor from consistent slot deployment and targets',
        best_formats: ['dynasty', 'redraft', 'bestball'],
      },
      common_failure_modes: ['nickel corner matchups', 'aDOT too low for ceiling games', 'target competition'],
      common_upside_triggers: ['linebacker coverage matchups', 'red-zone target consolidation', 'high-pace offense'],
      fallback_adjacent_roles: ['WR_FLANKER_CHAIN_MOVER', 'WR_SLOT_GADGET'],
    }),
    role({
      role_id: 'WR_FIELD_STRETCH_Z',
      position: 'WR',
      family: 'Wide Receiver',
      label: 'Field Stretch Z',
      description: 'Z alignment speed receiver used to stress coverage vertically.',
      key_metrics: ['deep_target_rate', 'motion_rate', 'boundary_rate', 'adot'],
      short_definition: 'Speed-first Z receiver who stretches the field vertically and wins with motion/deep routes.',
      usage_signature: {
        elevated: ['deep_target_rate', 'motion_rate', 'adot'],
        suppressed: ['slot_rate', 'red_zone_target_share'],
      },
      core_traits: ['top-end speed', 'motion deployment', 'deep-ball tracking', 'vertical route tree'],
      opportunity_profile: { snap_share: 'PARTIAL', pass_game_involved: true, rush_game_involved: false, red_zone_relevant: false },
      stability_profile: { week_to_week: 'LOW', season_to_season: 'MEDIUM', scheme_sensitive: true },
      fantasy_translation: {
        upside_driver: 'Explosive deep plays with high yards-per-target',
        floor_profile: 'Low floor; volatile target volume',
        best_formats: ['bestball'],
      },
      common_failure_modes: ['deep-ball variance', 'low target volume', 'game-script negative effect'],
      common_upside_triggers: ['favorable single-high matchups', 'improved target share', 'QB deep-ball accuracy'],
      fallback_adjacent_roles: ['WR_VERTICAL_X', 'WR_SLOT_GADGET'],
    }),
    role({
      role_id: 'WR_SLOT_GADGET',
      position: 'WR',
      family: 'Wide Receiver',
      label: 'Slot Gadget',
      description: 'Motion-heavy slot WR with manufactured-touch deployment and lower route load.',
      key_metrics: ['slot_rate', 'motion_rate', 'route_participation', 'adot'],
      short_definition: 'Manufactured-touch slot weapon with heavy motion and scheme-dependent deployment.',
      usage_signature: {
        elevated: ['slot_rate', 'motion_rate', 'screen_target_rate'],
        suppressed: ['route_participation', 'deep_target_rate', 'adot'],
      },
      core_traits: ['motion usage', 'after-catch ability', 'manufactured touches', 'scheme-fit deployment'],
      opportunity_profile: { snap_share: 'PARTIAL', pass_game_involved: true, rush_game_involved: false, red_zone_relevant: false },
      stability_profile: { week_to_week: 'LOW', season_to_season: 'LOW', scheme_sensitive: true },
      fantasy_translation: {
        upside_driver: 'YAC and manufactured touches in favorable game scripts',
        floor_profile: 'Low floor; volume dependent on play design',
        best_formats: ['bestball'],
      },
      common_failure_modes: ['low route participation limits target ceiling', 'coaching changes remove gadget role', 'efficiency regression'],
      common_upside_triggers: ['creative play-caller', 'rushing involvement (jet sweeps)', 'expanded route role'],
      fallback_adjacent_roles: ['WR_BIG_SLOT_HUB', 'WR_FIELD_STRETCH_Z'],
    }),

    // ── Tight Ends ────────────────────────────────────────────────────────
    role({
      role_id: 'TE_INLINE_ANCHOR',
      position: 'TE',
      family: 'Tight End',
      label: 'Inline Anchor',
      description: 'Inline TE with lower route volume and strong run-game attachment.',
      key_metrics: ['inline_rate', 'route_participation', 'adot', 'red_zone_target_share'],
      short_definition: 'Blocking-first TE who lines up inline and has limited but present receiving role.',
      usage_signature: {
        elevated: ['inline_rate'],
        suppressed: ['route_participation', 'target_share', 'slot_rate'],
      },
      core_traits: ['run blocking', 'inline alignment', 'underneath targets', 'limited route tree'],
      opportunity_profile: { snap_share: 'FULL', pass_game_involved: false, rush_game_involved: true, red_zone_relevant: false },
      stability_profile: { week_to_week: 'HIGH', season_to_season: 'HIGH', scheme_sensitive: true },
      fantasy_translation: {
        upside_driver: 'Red-zone TD opportunities from inline alignment',
        floor_profile: 'Very low fantasy floor due to limited targets',
        best_formats: [],
      },
      common_failure_modes: ['too few targets for fantasy relevance', 'TD drought', 'scheme de-emphasizes TE targets'],
      common_upside_triggers: ['red-zone target role expansion', 'injury to move TE on roster', 'improved passing offense'],
      fallback_adjacent_roles: ['TE_RED_ZONE_POWER', 'TE_MOVE_MISMATCH'],
    }),
    role({
      role_id: 'TE_MOVE_MISMATCH',
      position: 'TE',
      family: 'Tight End',
      label: 'Move Mismatch',
      description: 'Route-oriented TE deployed flexed/off-ball to create coverage mismatches.',
      key_metrics: ['inline_rate', 'route_participation', 'adot', 'slot_rate'],
      short_definition: 'Receiving-first TE who aligns off-ball and creates mismatches in the passing game.',
      usage_signature: {
        elevated: ['route_participation', 'slot_rate', 'target_share', 'targets_per_route'],
        suppressed: ['inline_rate'],
      },
      core_traits: ['route running', 'off-ball alignment', 'size-speed mismatch', 'seam threat'],
      opportunity_profile: { snap_share: 'FULL', pass_game_involved: true, rush_game_involved: false, red_zone_relevant: true },
      stability_profile: { week_to_week: 'MEDIUM', season_to_season: 'MEDIUM', scheme_sensitive: false },
      fantasy_translation: {
        upside_driver: 'Target volume from pass-game usage at premium position',
        floor_profile: 'Moderate floor from route participation and targets',
        best_formats: ['dynasty', 'redraft', 'bestball'],
      },
      common_failure_modes: ['efficiency regression', 'target competition', 'red-zone role given to other TE'],
      common_upside_triggers: ['target share consolidation', 'red-zone role expansion', 'favorable LB/S matchups'],
      fallback_adjacent_roles: ['TE_RED_ZONE_POWER', 'TE_INLINE_ANCHOR'],
    }),
    role({
      role_id: 'TE_RED_ZONE_POWER',
      position: 'TE',
      family: 'Tight End',
      label: 'Red Zone Power',
      description: 'Touchdown-specialist TE with concentrated red-zone target role.',
      key_metrics: ['red_zone_target_share', 'inline_rate', 'route_participation', 'adot'],
      short_definition: 'Red-zone specialist TE whose fantasy value is concentrated in scoring opportunities.',
      usage_signature: {
        elevated: ['red_zone_target_share', 'inline_rate'],
        suppressed: ['slot_rate'],
      },
      core_traits: ['red-zone target magnet', 'scoring specialist', 'inline/detached versatility', 'end-zone body control'],
      opportunity_profile: { snap_share: 'PARTIAL', pass_game_involved: true, rush_game_involved: true, red_zone_relevant: true },
      stability_profile: { week_to_week: 'LOW', season_to_season: 'MEDIUM', scheme_sensitive: true },
      fantasy_translation: {
        upside_driver: 'TD volume from red-zone target concentration',
        floor_profile: 'Low floor; very TD-dependent scoring profile',
        best_formats: ['bestball'],
      },
      common_failure_modes: ['TD variance', 'low between-the-20s usage', 'red-zone target competition'],
      common_upside_triggers: ['team red-zone efficiency', 'expanded route role', 'injuries to other pass catchers'],
      fallback_adjacent_roles: ['TE_INLINE_ANCHOR', 'TE_MOVE_MISMATCH'],
    }),

    // ── Unknown / Insufficient Data ───────────────────────────────────────
    role({
      role_id: 'QB_UNKNOWN',
      position: 'QB',
      family: 'Quarterback',
      label: 'Unknown QB',
      description: 'Insufficient data to classify quarterback role.',
      key_metrics: [],
      short_definition: 'QB with insufficient usage data to determine a football archetype.',
      usage_signature: { elevated: [], suppressed: [] },
      core_traits: [],
      opportunity_profile: { snap_share: 'PARTIAL', pass_game_involved: true, rush_game_involved: false, red_zone_relevant: false },
      stability_profile: { week_to_week: 'LOW', season_to_season: 'LOW', scheme_sensitive: false },
      fantasy_translation: {
        upside_driver: 'Unknown — insufficient data',
        floor_profile: 'Unknown — insufficient data',
        best_formats: [],
      },
      common_failure_modes: [],
      common_upside_triggers: [],
      fallback_adjacent_roles: [],
    }),
    role({
      role_id: 'RB_UNKNOWN',
      position: 'RB',
      family: 'Running Back',
      label: 'Unknown RB',
      description: 'Insufficient data to classify running back role.',
      key_metrics: [],
      short_definition: 'RB with insufficient usage data to determine a football archetype.',
      usage_signature: { elevated: [], suppressed: [] },
      core_traits: [],
      opportunity_profile: { snap_share: 'PARTIAL', pass_game_involved: false, rush_game_involved: true, red_zone_relevant: false },
      stability_profile: { week_to_week: 'LOW', season_to_season: 'LOW', scheme_sensitive: false },
      fantasy_translation: {
        upside_driver: 'Unknown — insufficient data',
        floor_profile: 'Unknown — insufficient data',
        best_formats: [],
      },
      common_failure_modes: [],
      common_upside_triggers: [],
      fallback_adjacent_roles: [],
    }),
    role({
      role_id: 'WR_UNKNOWN',
      position: 'WR',
      family: 'Wide Receiver',
      label: 'Unknown WR',
      description: 'Insufficient data to classify wide receiver role.',
      key_metrics: [],
      short_definition: 'WR with insufficient usage data to determine a football archetype.',
      usage_signature: { elevated: [], suppressed: [] },
      core_traits: [],
      opportunity_profile: { snap_share: 'PARTIAL', pass_game_involved: true, rush_game_involved: false, red_zone_relevant: false },
      stability_profile: { week_to_week: 'LOW', season_to_season: 'LOW', scheme_sensitive: false },
      fantasy_translation: {
        upside_driver: 'Unknown — insufficient data',
        floor_profile: 'Unknown — insufficient data',
        best_formats: [],
      },
      common_failure_modes: [],
      common_upside_triggers: [],
      fallback_adjacent_roles: [],
    }),
    role({
      role_id: 'TE_UNKNOWN',
      position: 'TE',
      family: 'Tight End',
      label: 'Unknown TE',
      description: 'Insufficient data to classify tight end role.',
      key_metrics: [],
      short_definition: 'TE with insufficient usage data to determine a football archetype.',
      usage_signature: { elevated: [], suppressed: [] },
      core_traits: [],
      opportunity_profile: { snap_share: 'PARTIAL', pass_game_involved: false, rush_game_involved: false, red_zone_relevant: false },
      stability_profile: { week_to_week: 'LOW', season_to_season: 'LOW', scheme_sensitive: false },
      fantasy_translation: {
        upside_driver: 'Unknown — insufficient data',
        floor_profile: 'Unknown — insufficient data',
        best_formats: [],
      },
      common_failure_modes: [],
      common_upside_triggers: [],
      fallback_adjacent_roles: [],
    }),
  ]) as RoleOntology['roles'],
};
