ALTER TABLE playbook_entries
  ADD COLUMN IF NOT EXISTS outcome TEXT,
  ADD COLUMN IF NOT EXISTS regret_score INT,
  ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS forge_before NUMERIC,
  ADD COLUMN IF NOT EXISTS forge_after NUMERIC,
  ADD COLUMN IF NOT EXISTS tier_before TEXT,
  ADD COLUMN IF NOT EXISTS tier_after TEXT;
