/**
 * QB Batch Input for 2024 Season
 * Top 25 QB prospects for context score evaluation
 */

export const qbBatchInput = [
  {
    playerName: "Josh Allen",
    season: 2024,
    position: "QB",
    passingYards: 4306,
    passingTDs: 28,
    interceptions: 6,
    rushingYards: 553,
    rushingTDs: 15,
    completionPercentage: 63.6,
    epaPerPlay: 0.25,
    qbr: 81.2,
    scrambleRate: 0.18,
    rushYPG: 32.5,
    yardsPerCarry: 4.2,
    explosiveRushRate: 0.22,
    cpoe: 0.025,
    adjustedCompletionPct: 0.645,
    deepAccuracyRate: 0.48,
    pressureToSackRate: 0.15,
    team: {
      passBlockGrade: 78,
      passBlockWinRate: 0.62,
      pressureRateAllowed: 0.31,
      pressureRateOverExpected: -0.05,
      wrYPRR: 1.85,
      wr1DRR: 0.095,
      yardsPerTarget: 7.2,
      yacPerReception: 5.8,
      contestedCatchRate: 0.58,
      routeWinRateRanks: [75, 82, 68, 55],
      offseasonWRUpgrades: ["Amari Cooper trade", "Keon Coleman draft"]
    }
  },
  {
    playerName: "Lamar Jackson",
    season: 2024,
    position: "QB",
    passingYards: 3678,
    passingTDs: 40,
    interceptions: 4,
    rushingYards: 915,
    rushingTDs: 3,
    completionPercentage: 66.7,
    epaPerPlay: 0.32,
    qbr: 85.4,
    scrambleRate: 0.25,
    rushYPG: 53.8,
    yardsPerCarry: 5.6,
    explosiveRushRate: 0.31,
    cpoe: 0.045,
    adjustedCompletionPct: 0.678,
    deepAccuracyRate: 0.52,
    pressureToSackRate: 0.12,
    team: {
      passBlockGrade: 72,
      passBlockWinRate: 0.58,
      pressureRateAllowed: 0.35,
      pressureRateOverExpected: 0.02,
      wrYPRR: 1.92,
      wr1DRR: 0.088,
      yardsPerTarget: 7.8,
      yacPerReception: 6.2,
      contestedCatchRate: 0.62,
      routeWinRateRanks: [68, 75, 72, 58],
      offseasonWRUpgrades: ["Zay Flowers development", "Tight end upgrade"]
    }
  },
  {
    playerName: "Jayden Daniels",
    season: 2024,
    position: "QB",
    passingYards: 3568,
    passingTDs: 25,
    interceptions: 9,
    rushingYards: 891,
    rushingTDs: 6,
    completionPercentage: 69.0,
    epaPerPlay: 0.23,
    qbr: 78.5,
    scrambleRate: 0.22,
    rushYPG: 52.4,
    yardsPerCarry: 5.3,
    explosiveRushRate: 0.28,
    cpoe: 0.038,
    adjustedCompletionPct: 0.695,
    deepAccuracyRate: 0.45,
    pressureToSackRate: 0.11,
    team: {
      passBlockGrade: 68,
      passBlockWinRate: 0.55,
      pressureRateAllowed: 0.38,
      pressureRateOverExpected: 0.05,
      wrYPRR: 1.78,
      wr1DRR: 0.082,
      yardsPerTarget: 6.9,
      yacPerReception: 5.4,
      contestedCatchRate: 0.55,
      routeWinRateRanks: [62, 68, 65, 52],
      offseasonWRUpgrades: ["Rookie development", "Terry McLaurin security"]
    }
  },
  {
    playerName: "Patrick Mahomes",
    season: 2024,
    position: "QB",
    passingYards: 4183,
    passingTDs: 26,
    interceptions: 11,
    rushingYards: 417,
    rushingTDs: 2,
    completionPercentage: 67.5,
    epaPerPlay: 0.21,
    qbr: 76.8,
    scrambleRate: 0.14,
    rushYPG: 24.5,
    yardsPerCarry: 4.8,
    explosiveRushRate: 0.18,
    cpoe: 0.032,
    adjustedCompletionPct: 0.685,
    deepAccuracyRate: 0.50,
    pressureToSackRate: 0.13,
    team: {
      passBlockGrade: 75,
      passBlockWinRate: 0.61,
      pressureRateAllowed: 0.29,
      pressureRateOverExpected: -0.08,
      wrYPRR: 1.95,
      wr1DRR: 0.105,
      yardsPerTarget: 8.1,
      yacPerReception: 6.5,
      contestedCatchRate: 0.65,
      routeWinRateRanks: [88, 92, 85, 78],
      offseasonWRUpgrades: ["Xavier Worthy draft", "Hollywood Brown health"]
    }
  },
  {
    playerName: "Joe Burrow",
    season: 2024,
    position: "QB",
    passingYards: 4918,
    passingTDs: 43,
    interceptions: 7,
    rushingYards: 117,
    rushingTDs: 3,
    completionPercentage: 70.4,
    epaPerPlay: 0.28,
    qbr: 82.1,
    scrambleRate: 0.08,
    rushYPG: 6.9,
    yardsPerCarry: 3.2,
    explosiveRushRate: 0.08,
    cpoe: 0.058,
    adjustedCompletionPct: 0.715,
    deepAccuracyRate: 0.56,
    pressureToSackRate: 0.16,
    team: {
      passBlockGrade: 65,
      passBlockWinRate: 0.52,
      pressureRateAllowed: 0.42,
      pressureRateOverExpected: 0.08,
      wrYPRR: 2.15,
      wr1DRR: 0.125,
      yardsPerTarget: 8.8,
      yacPerReception: 6.8,
      contestedCatchRate: 0.68,
      routeWinRateRanks: [95, 88, 92, 85],
      offseasonWRUpgrades: ["Ja'Marr Chase extension", "Tee Higgins security"]
    }
  },
  {
    playerName: "Jalen Hurts",
    season: 2024,
    position: "QB",
    passingYards: 3858,
    passingTDs: 15,
    interceptions: 5,
    rushingYards: 630,
    rushingTDs: 14,
    completionPercentage: 68.7,
    epaPerPlay: 0.18,
    qbr: 74.2,
    scrambleRate: 0.19,
    rushYPG: 37.1,
    yardsPerCarry: 5.1,
    explosiveRushRate: 0.24,
    cpoe: 0.028,
    adjustedCompletionPct: 0.695,
    deepAccuracyRate: 0.42,
    pressureToSackRate: 0.14,
    team: {
      passBlockGrade: 70,
      passBlockWinRate: 0.57,
      pressureRateAllowed: 0.34,
      pressureRateOverExpected: 0.01,
      wrYPRR: 1.88,
      wr1DRR: 0.092,
      yardsPerTarget: 7.5,
      yacPerReception: 5.9,
      contestedCatchRate: 0.60,
      routeWinRateRanks: [78, 82, 75, 65],
      offseasonWRUpgrades: ["A.J. Brown health", "DeVonta Smith consistency"]
    }
  },
  {
    playerName: "Caleb Williams",
    season: 2024,
    position: "QB",
    passingYards: 3541,
    passingTDs: 20,
    interceptions: 6,
    rushingYards: 489,
    rushingTDs: 4,
    completionPercentage: 62.5,
    epaPerPlay: 0.12,
    qbr: 68.9,
    scrambleRate: 0.16,
    rushYPG: 28.8,
    yardsPerCarry: 4.7,
    explosiveRushRate: 0.19,
    cpoe: 0.018,
    adjustedCompletionPct: 0.635,
    deepAccuracyRate: 0.41,
    pressureToSackRate: 0.19,
    team: {
      passBlockGrade: 62,
      passBlockWinRate: 0.48,
      pressureRateAllowed: 0.45,
      pressureRateOverExpected: 0.12,
      wrYPRR: 1.65,
      wr1DRR: 0.075,
      yardsPerTarget: 6.8,
      yacPerReception: 5.2,
      contestedCatchRate: 0.52,
      routeWinRateRanks: [58, 62, 55, 48],
      offseasonWRUpgrades: ["Rookie weapons", "Rome Odunze draft"]
    }
  },
  {
    playerName: "Dak Prescott",
    season: 2024,
    position: "QB",
    passingYards: 3304,
    passingTDs: 29,
    interceptions: 11,
    rushingYards: 105,
    rushingTDs: 2,
    completionPercentage: 64.7,
    epaPerPlay: 0.19,
    qbr: 71.5,
    scrambleRate: 0.09,
    rushYPG: 6.2,
    yardsPerCarry: 3.8,
    explosiveRushRate: 0.11,
    cpoe: 0.025,
    adjustedCompletionPct: 0.658,
    deepAccuracyRate: 0.47,
    pressureToSackRate: 0.17,
    team: {
      passBlockGrade: 73,
      passBlockWinRate: 0.59,
      pressureRateAllowed: 0.32,
      pressureRateOverExpected: -0.02,
      wrYPRR: 1.82,
      wr1DRR: 0.089,
      yardsPerTarget: 7.3,
      yacPerReception: 5.7,
      contestedCatchRate: 0.57,
      routeWinRateRanks: [72, 75, 68, 62],
      offseasonWRUpgrades: ["CeeDee Lamb extension", "Weapon development"]
    }
  },
  {
    playerName: "Tua Tagovailoa",
    season: 2024,
    position: "QB",
    passingYards: 2867,
    passingTDs: 19,
    interceptions: 7,
    rushingYards: 42,
    rushingTDs: 1,
    completionPercentage: 69.3,
    epaPerPlay: 0.16,
    qbr: 72.8,
    scrambleRate: 0.04,
    rushYPG: 2.5,
    yardsPerCarry: 2.8,
    explosiveRushRate: 0.06,
    cpoe: 0.048,
    adjustedCompletionPct: 0.705,
    deepAccuracyRate: 0.44,
    pressureToSackRate: 0.22,
    team: {
      passBlockGrade: 66,
      passBlockWinRate: 0.51,
      pressureRateAllowed: 0.41,
      pressureRateOverExpected: 0.06,
      wrYPRR: 2.05,
      wr1DRR: 0.098,
      yardsPerTarget: 8.2,
      yacPerReception: 6.9,
      contestedCatchRate: 0.61,
      routeWinRateRanks: [85, 88, 82, 75],
      offseasonWRUpgrades: ["Tyreek Hill prime", "Jaylen Waddle development"]
    }
  },
  {
    playerName: "Brock Purdy",
    season: 2024,
    position: "QB",
    passingYards: 3864,
    passingTDs: 20,
    interceptions: 12,
    rushingYards: 144,
    rushingTDs: 2,
    completionPercentage: 66.8,
    epaPerPlay: 0.14,
    qbr: 69.4,
    scrambleRate: 0.07,
    rushYPG: 8.5,
    yardsPerCarry: 4.1,
    explosiveRushRate: 0.09,
    cpoe: 0.035,
    adjustedCompletionPct: 0.678,
    deepAccuracyRate: 0.48,
    pressureToSackRate: 0.15,
    team: {
      passBlockGrade: 76,
      passBlockWinRate: 0.63,
      pressureRateAllowed: 0.28,
      pressureRateOverExpected: -0.09,
      wrYPRR: 1.98,
      wr1DRR: 0.112,
      yardsPerTarget: 8.5,
      yacPerReception: 7.2,
      contestedCatchRate: 0.66,
      routeWinRateRanks: [90, 92, 88, 82],
      offseasonWRUpgrades: ["Elite weapons", "System familiarity"]
    }
  },
  {
    playerName: "Jordan Love",
    season: 2024,
    position: "QB",
    passingYards: 3389,
    passingTDs: 25,
    interceptions: 10,
    rushingYards: 247,
    rushingTDs: 4,
    completionPercentage: 63.7,
    epaPerPlay: 0.15,
    qbr: 70.2,
    scrambleRate: 0.11,
    rushYPG: 14.5,
    yardsPerCarry: 4.5,
    explosiveRushRate: 0.15,
    cpoe: 0.022,
    adjustedCompletionPct: 0.648,
    deepAccuracyRate: 0.46,
    pressureToSackRate: 0.18,
    team: {
      passBlockGrade: 71,
      passBlockWinRate: 0.56,
      pressureRateAllowed: 0.36,
      pressureRateOverExpected: 0.03,
      wrYPRR: 1.75,
      wr1DRR: 0.085,
      yardsPerTarget: 7.1,
      yacPerReception: 5.6,
      contestedCatchRate: 0.56,
      routeWinRateRanks: [65, 68, 62, 55],
      offseasonWRUpgrades: ["Jayden Reed development", "Christian Watson health"]
    }
  },
  {
    playerName: "Kyler Murray",
    season: 2024,
    position: "QB",
    passingYards: 3926,
    passingTDs: 22,
    interceptions: 9,
    rushingYards: 564,
    rushingTDs: 4,
    completionPercentage: 66.4,
    epaPerPlay: 0.13,
    qbr: 68.7,
    scrambleRate: 0.21,
    rushYPG: 33.2,
    yardsPerCarry: 4.9,
    explosiveRushRate: 0.26,
    cpoe: 0.028,
    adjustedCompletionPct: 0.675,
    deepAccuracyRate: 0.43,
    pressureToSackRate: 0.14,
    team: {
      passBlockGrade: 64,
      passBlockWinRate: 0.49,
      pressureRateAllowed: 0.44,
      pressureRateOverExpected: 0.09,
      wrYPRR: 1.68,
      wr1DRR: 0.078,
      yardsPerTarget: 6.7,
      yacPerReception: 5.3,
      contestedCatchRate: 0.53,
      routeWinRateRanks: [55, 58, 52, 48],
      offseasonWRUpgrades: ["Marvin Harrison Jr. draft", "Rookie weapons"]
    }
  },
  {
    playerName: "Sam Darnold",
    season: 2024,
    position: "QB",
    passingYards: 4319,
    passingTDs: 35,
    interceptions: 12,
    rushingYards: 148,
    rushingTDs: 5,
    completionPercentage: 66.2,
    epaPerPlay: 0.17,
    qbr: 73.6,
    scrambleRate: 0.08,
    rushYPG: 8.7,
    yardsPerCarry: 3.9,
    explosiveRushRate: 0.12,
    cpoe: 0.032,
    adjustedCompletionPct: 0.672,
    deepAccuracyRate: 0.49,
    pressureToSackRate: 0.16,
    team: {
      passBlockGrade: 69,
      passBlockWinRate: 0.54,
      pressureRateAllowed: 0.37,
      pressureRateOverExpected: 0.04,
      wrYPRR: 1.88,
      wr1DRR: 0.095,
      yardsPerTarget: 7.6,
      yacPerReception: 6.1,
      contestedCatchRate: 0.59,
      routeWinRateRanks: [75, 78, 72, 65],
      offseasonWRUpgrades: ["Justin Jefferson elite", "Jordan Addison development"]
    }
  },
  {
    playerName: "Geno Smith",
    season: 2024,
    position: "QB",
    passingYards: 3623,
    passingTDs: 15,
    interceptions: 15,
    rushingYards: 229,
    rushingTDs: 1,
    completionPercentage: 63.3,
    epaPerPlay: 0.08,
    qbr: 64.5,
    scrambleRate: 0.10,
    rushYPG: 13.5,
    yardsPerCarry: 4.2,
    explosiveRushRate: 0.13,
    cpoe: 0.015,
    adjustedCompletionPct: 0.645,
    deepAccuracyRate: 0.40,
    pressureToSackRate: 0.21,
    team: {
      passBlockGrade: 67,
      passBlockWinRate: 0.53,
      pressureRateAllowed: 0.39,
      pressureRateOverExpected: 0.07,
      wrYPRR: 1.72,
      wr1DRR: 0.081,
      yardsPerTarget: 6.9,
      yacPerReception: 5.4,
      contestedCatchRate: 0.54,
      routeWinRateRanks: [58, 62, 55, 48],
      offseasonWRUpgrades: ["DK Metcalf security", "Tyler Lockett veteran"]
    }
  },
  {
    playerName: "Drake Maye",
    season: 2024,
    position: "QB",
    passingYards: 2276,
    passingTDs: 15,
    interceptions: 10,
    rushingYards: 421,
    rushingTDs: 1,
    completionPercentage: 66.6,
    epaPerPlay: 0.09,
    qbr: 66.1,
    scrambleRate: 0.17,
    rushYPG: 24.8,
    yardsPerCarry: 4.8,
    explosiveRushRate: 0.21,
    cpoe: 0.028,
    adjustedCompletionPct: 0.678,
    deepAccuracyRate: 0.44,
    pressureToSackRate: 0.20,
    team: {
      passBlockGrade: 58,
      passBlockWinRate: 0.44,
      pressureRateAllowed: 0.48,
      pressureRateOverExpected: 0.15,
      wrYPRR: 1.52,
      wr1DRR: 0.068,
      yardsPerTarget: 6.2,
      yacPerReception: 4.8,
      contestedCatchRate: 0.48,
      routeWinRateRanks: [42, 45, 38, 35],
      offseasonWRUpgrades: ["Rookie development", "Weapon acquisition needs"]
    }
  },
  {
    playerName: "Bo Nix",
    season: 2024,
    position: "QB",
    passingYards: 3775,
    passingTDs: 29,
    interceptions: 12,
    rushingYards: 430,
    rushingTDs: 4,
    completionPercentage: 66.3,
    epaPerPlay: 0.11,
    qbr: 67.8,
    scrambleRate: 0.14,
    rushYPG: 25.3,
    yardsPerCarry: 4.6,
    explosiveRushRate: 0.17,
    cpoe: 0.025,
    adjustedCompletionPct: 0.675,
    deepAccuracyRate: 0.42,
    pressureToSackRate: 0.17,
    team: {
      passBlockGrade: 63,
      passBlockWinRate: 0.50,
      pressureRateAllowed: 0.43,
      pressureRateOverExpected: 0.10,
      wrYPRR: 1.62,
      wr1DRR: 0.072,
      yardsPerTarget: 6.5,
      yacPerReception: 5.1,
      contestedCatchRate: 0.51,
      routeWinRateRanks: [48, 52, 45, 38],
      offseasonWRUpgrades: ["Courtland Sutton veteran", "Rookie development"]
    }
  },
  {
    playerName: "C.J. Stroud",
    season: 2024,
    position: "QB",
    passingYards: 3727,
    passingTDs: 20,
    interceptions: 12,
    rushingYards: 167,
    rushingTDs: 3,
    completionPercentage: 63.3,
    epaPerPlay: 0.10,
    qbr: 66.9,
    scrambleRate: 0.09,
    rushYPG: 9.8,
    yardsPerCarry: 3.8,
    explosiveRushRate: 0.10,
    cpoe: 0.018,
    adjustedCompletionPct: 0.645,
    deepAccuracyRate: 0.45,
    pressureToSackRate: 0.18,
    team: {
      passBlockGrade: 61,
      passBlockWinRate: 0.47,
      pressureRateAllowed: 0.46,
      pressureRateOverExpected: 0.13,
      wrYPRR: 1.58,
      wr1DRR: 0.070,
      yardsPerTarget: 6.4,
      yacPerReception: 5.0,
      contestedCatchRate: 0.49,
      routeWinRateRanks: [45, 48, 42, 35],
      offseasonWRUpgrades: ["Stefon Diggs trade", "Nico Collins development"]
    }
  },
  {
    playerName: "Anthony Richardson",
    season: 2024,
    position: "QB",
    passingYards: 1814,
    passingTDs: 8,
    interceptions: 12,
    rushingYards: 499,
    rushingTDs: 6,
    completionPercentage: 47.7,
    epaPerPlay: -0.05,
    qbr: 52.4,
    scrambleRate: 0.23,
    rushYPG: 41.6,
    yardsPerCarry: 5.8,
    explosiveRushRate: 0.32,
    cpoe: -0.045,
    adjustedCompletionPct: 0.485,
    deepAccuracyRate: 0.38,
    pressureToSackRate: 0.16,
    team: {
      passBlockGrade: 65,
      passBlockWinRate: 0.51,
      pressureRateAllowed: 0.40,
      pressureRateOverExpected: 0.07,
      wrYPRR: 1.68,
      wr1DRR: 0.075,
      yardsPerTarget: 6.8,
      yacPerReception: 5.2,
      contestedCatchRate: 0.52,
      routeWinRateRanks: [52, 55, 48, 42],
      offseasonWRUpgrades: ["Rookie development", "Weapon development"]
    }
  },
  {
    playerName: "Russell Wilson",
    season: 2024,
    position: "QB",
    passingYards: 2482,
    passingTDs: 16,
    interceptions: 5,
    rushingYards: 103,
    rushingTDs: 3,
    completionPercentage: 63.7,
    epaPerPlay: 0.14,
    qbr: 70.1,
    scrambleRate: 0.08,
    rushYPG: 6.4,
    yardsPerCarry: 4.1,
    explosiveRushRate: 0.11,
    cpoe: 0.025,
    adjustedCompletionPct: 0.648,
    deepAccuracyRate: 0.48,
    pressureToSackRate: 0.15,
    team: {
      passBlockGrade: 74,
      passBlockWinRate: 0.60,
      pressureRateAllowed: 0.30,
      pressureRateOverExpected: -0.06,
      wrYPRR: 1.85,
      wr1DRR: 0.092,
      yardsPerTarget: 7.4,
      yacPerReception: 5.8,
      contestedCatchRate: 0.58,
      routeWinRateRanks: [72, 75, 68, 62],
      offseasonWRUpgrades: ["George Pickens development", "Veteran presence"]
    }
  },
  {
    playerName: "Daniel Jones",
    season: 2024,
    position: "QB",
    passingYards: 2070,
    passingTDs: 8,
    interceptions: 7,
    rushingYards: 265,
    rushingTDs: 2,
    completionPercentage: 63.3,
    epaPerPlay: 0.02,
    qbr: 58.6,
    scrambleRate: 0.15,
    rushYPG: 24.1,
    yardsPerCarry: 4.7,
    explosiveRushRate: 0.18,
    cpoe: 0.012,
    adjustedCompletionPct: 0.645,
    deepAccuracyRate: 0.38,
    pressureToSackRate: 0.22,
    team: {
      passBlockGrade: 59,
      passBlockWinRate: 0.46,
      pressureRateAllowed: 0.47,
      pressureRateOverExpected: 0.14,
      wrYPRR: 1.48,
      wr1DRR: 0.065,
      yardsPerTarget: 6.1,
      yacPerReception: 4.7,
      contestedCatchRate: 0.47,
      routeWinRateRanks: [38, 42, 35, 32],
      offseasonWRUpgrades: ["Malik Nabers draft", "Rookie weapons"]
    }
  },
  {
    playerName: "Aaron Rodgers",
    season: 2024,
    position: "QB",
    passingYards: 3897,
    passingTDs: 28,
    interceptions: 11,
    rushingYards: 54,
    rushingTDs: 0,
    completionPercentage: 63.4,
    epaPerPlay: 0.12,
    qbr: 68.2,
    scrambleRate: 0.05,
    rushYPG: 3.2,
    yardsPerCarry: 2.9,
    explosiveRushRate: 0.07,
    cpoe: 0.028,
    adjustedCompletionPct: 0.645,
    deepAccuracyRate: 0.51,
    pressureToSackRate: 0.19,
    team: {
      passBlockGrade: 66,
      passBlockWinRate: 0.52,
      pressureRateAllowed: 0.41,
      pressureRateOverExpected: 0.08,
      wrYPRR: 1.78,
      wr1DRR: 0.087,
      yardsPerTarget: 7.2,
      yacPerReception: 5.6,
      contestedCatchRate: 0.56,
      routeWinRateRanks: [65, 68, 62, 55],
      offseasonWRUpgrades: ["Davante Adams reunion", "Weapon familiarity"]
    }
  },
  {
    playerName: "Justin Herbert",
    season: 2024,
    position: "QB",
    passingYards: 3870,
    passingTDs: 23,
    interceptions: 3,
    rushingYards: 190,
    rushingTDs: 1,
    completionPercentage: 66.7,
    epaPerPlay: 0.16,
    qbr: 72.4,
    scrambleRate: 0.09,
    rushYPG: 11.2,
    yardsPerCarry: 4.3,
    explosiveRushRate: 0.12,
    cpoe: 0.038,
    adjustedCompletionPct: 0.678,
    deepAccuracyRate: 0.49,
    pressureToSackRate: 0.14,
    team: {
      passBlockGrade: 68,
      passBlockWinRate: 0.54,
      pressureRateAllowed: 0.37,
      pressureRateOverExpected: 0.04,
      wrYPRR: 1.72,
      wr1DRR: 0.083,
      yardsPerTarget: 7.0,
      yacPerReception: 5.5,
      contestedCatchRate: 0.55,
      routeWinRateRanks: [58, 62, 55, 48],
      offseasonWRUpgrades: ["Ladd McConkey draft", "Rookie weapons"]
    }
  },
  {
    playerName: "Trevor Lawrence",
    season: 2024,
    position: "QB",
    passingYards: 4045,
    passingTDs: 21,
    interceptions: 14,
    rushingYards: 308,
    rushingTDs: 1,
    completionPercentage: 62.8,
    epaPerPlay: 0.07,
    qbr: 63.8,
    scrambleRate: 0.12,
    rushYPG: 18.1,
    yardsPerCarry: 4.4,
    explosiveRushRate: 0.14,
    cpoe: 0.015,
    adjustedCompletionPct: 0.638,
    deepAccuracyRate: 0.43,
    pressureToSackRate: 0.20,
    team: {
      passBlockGrade: 61,
      passBlockWinRate: 0.48,
      pressureRateAllowed: 0.44,
      pressureRateOverExpected: 0.11,
      wrYPRR: 1.62,
      wr1DRR: 0.074,
      yardsPerTarget: 6.6,
      yacPerReception: 5.1,
      contestedCatchRate: 0.51,
      routeWinRateRanks: [48, 52, 45, 38],
      offseasonWRUpgrades: ["Brian Thomas Jr. draft", "Rookie development"]
    }
  },
  {
    playerName: "Will Levis",
    season: 2024,
    position: "QB",
    passingYards: 1808,
    passingTDs: 7,
    interceptions: 4,
    rushingYards: 168,
    rushingTDs: 3,
    completionPercentage: 64.7,
    epaPerPlay: 0.05,
    qbr: 61.2,
    scrambleRate: 0.13,
    rushYPG: 14.0,
    yardsPerCarry: 4.2,
    explosiveRushRate: 0.15,
    cpoe: 0.018,
    adjustedCompletionPct: 0.658,
    deepAccuracyRate: 0.41,
    pressureToSackRate: 0.18,
    team: {
      passBlockGrade: 64,
      passBlockWinRate: 0.50,
      pressureRateAllowed: 0.42,
      pressureRateOverExpected: 0.09,
      wrYPRR: 1.55,
      wr1DRR: 0.071,
      yardsPerTarget: 6.3,
      yacPerReception: 4.9,
      contestedCatchRate: 0.50,
      routeWinRateRanks: [45, 48, 42, 35],
      offseasonWRUpgrades: ["Calvin Ridley addition", "Weapon development"]
    }
  }
];

export default qbBatchInput;