export const ErrorCodes = {
  AUTH_MISSING_KEY: "AUTH_MISSING_KEY",
  AUTH_INVALID_KEY: "AUTH_INVALID_KEY",
  AUTH_REVOKED_KEY: "AUTH_REVOKED_KEY",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  UPSTREAM_TIMEOUT: "UPSTREAM_TIMEOUT",
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
